export default {
  questions: [
    {
      ShortTerm: [
        "How is [project] going? What could we do to make it better?",
        "Is there anything blocking you from getting your work done?",
        "What are your top priorities right now?",
        "Are there any projects you’d really like to work on if you were given the opportunity?",
        "What parts of your job would you like to deepen your skills in or get additional training in?",
        "Is any part of your project unclear or confusing?",
        "What have you learned this past week?",
        "Where did we see growth this week?",
        "How are you feeling about work?",
        "How are you going to approach this?",
        "How are you planning to balance work and personal life this year?",
        "How can I help…? (be more productive/happier at work/enjoy work more/etc)",
        "How do you feel about your work/life balance?",
        "How is your workload right now?",
        "If you could change one thing about your job today, what would you change?",
        "Is there anything that you need from me?",
        "Is there anything that you’re struggling with?",
        "Is there anything you’d like to be doing on your own time to relieve stress that you’re not getting to? How can I help you achieve those personal goals?",
        "What about work is frustrating?",
        "What about your job is most satisfying for you?",
        "What are 3 things could we do to improve your productivity if money was no object?",
        "What are the biggest time wasters for you each week?",
        "What are the most important things you will focus on before we meet next?",
        "What are you doing for yourself outside of work?",
        "What are your most significant accomplishments since we last met?",
        "What areas of your work are you confident about?",
        "What could we change about work that would improve the rest of your life?",
        "What do you do when you feel low energy or unmotivated?",
        "What does your ideal weekday look like?",
        "What is an ideal, productive day at work for you? Walk me through the day…",
        "What is the most important thing we need to discuss today?",
        "What makes you excited and motivated to work on a project?",
        "What obstacles are you encountering right now?",
        "What part of the day do you have the most energy and focus? When do you have the least? What changes could we make to your work schedule to accommodate this?",
        "What part of your work routine do you find is working best? What area do you want to improve?",
        "What questions do you have about this project?",
        "What stands in your way?",
        "What suggestions do you have?",
        "What was difficult this week? what have you learned?",
        "What were your biggest time wasters or roadblocks last week or the week before?",
        "What worries you?",
        "What worries you? What’s on your mind?",
        "What, if anything, did you used to do that you find you don’t have time for right now?",
        "What’s an inexpensive thing we could do to improve our office environment?",
        "When is your next vacation?",
        "When was your last vacation?",
        "When you get stuck on something, what is your process for getting unstuck? Who do you turn to for help?",
        "Which part of the day do you feel most productive? When do you feel that your energy and focus are at the lowest level? What are the changes that can be made so you can take the best out of a work day?"
      ]
    },
    {
      LongTerm: [
        "Do you have opportunities at work to learn and grow? What would you like to learn or get better at?",
        "Do you see yourself working here in three years? Why or why not?",
        "Do you believe there are good career opportunities at Stripe (e.g. stretch assignments, increased responsibility, and internal mobility)? If not, what opportunities would excite you?",
        "What do you want to be doing in 5 years? 10 years? 3 years?",
        "What are your long term goals? Have you thought about them?",
        "Do you feel like you’re making progress on your big goals here? Why or why not?",
        "What’s one thing we could do today to help you with your long term goals?",
        "Do you feel we’re helping you advance your career at a pace you would like?",
        "If you had millions of dollars, what would you do every day?",
        "What are your super powers? What powers would you like to develop?",
        "What are your big dreams in life? Are you making progress on them?",
        "Could you see yourself making progress on more of your goals here? What would need to change to do so?",
        "What work are you doing here that you feel is most in line with your long term goals?",
        "As a kid, what did you want to be when you grew up?"
      ]
    },
    {
      SelfImprovement: [
        "Do you feel challenged at work? Are you learning new things?",
        "What area of the company would you like to learn more about?",
        "What skills would you like to develop right now?",
        "When do you think you’re at your best?",
        "What is the most important thing to you in your work?",
        "What do you enjoy the most about your work?",
        "How do you like to be rewarded?",
        "What do you think is the most important thing for me to focus on when it comes to you and your role?",
        "Who in the company would you like to learn from? What do you want to learn?",
        "How do you prefer to receive feedback?",
        "Do you feel you’re getting enough feedback?",
        "What’s a recent situation you wish you handled differently? What would you change?",
        "What additional training or education would you like?",
        "Are there any roles in the company you’d like to learn more about?",
        "What do you think are the key skills for your role? How would you rate yourself for each of them?",
        "Is there an aspect of your job you would like more help or coaching?",
        "Looking back on the week, is there anything that could have gone better?",
        "Are there any events or training you’d like to attend to help you grow your skills?",
        "Are there any projects you’d really like to work on if you were given the opportunity?",
        "Could you see yourself making progress on more of your goals here? What would need to change to do so?",
        "Do you feel like you are learning at work? What are the new things you learned lately? What are the areas you want to learn about?",
        "Do you feel like you’re making progress on your big goals here? Why or why not?",
        "Do you feel we’re helping you advance your career at a pace you would like?",
        "Do you have the tools you need to reach your goals?",
        "During this meeting you’ve mentioned that you’d like to pursue X. What steps can you take toward that before our next 1-on-1?",
        "Have you ever felt undervalued here?",
        "Have you given any more thought to your long-term goals since our last meeting? What are your latest thoughts?",
        "How do you feel you are progressing in your career?",
        "How do you think about your progress on your big goals? What needs to be done to move towards the goals? What can we do to help?",
        "How do you think you did on your performance review this year? What do you think the results will be?",
        "How is your current work helping or hurting your professional development?",
        "If you were to create your ideal position, how would it differ from what you are currently doing?",
        "Imagine it’s two years from now, and things have gone well: What has been your role in that? What does your role look like?",
        "Is there a different way we can develop your skills outside of traditional training?",
        "Is there an aspect of your job you would like more help or coaching?",
        "Tell me about something new you learned since we met last.",
        "To help identify and clarify the goal: What do you want to achieve? What will you do to achieve it? When will you do it? Who do you need to involve? When should you see results?",
        "What about this goal is important to you and what will be different when you achieve the goal?",
        "What actions will you take before our next 1-on-1 to make progress on X? (Also discuss and agree on actions you will take to help.)",
        "What additional training or education would you like?",
        "What are some of the work projects you’re most proud of, and what do you think you might want to do next?",
        "What are the projects you would be interested in working on next?",
        "What are two to three new skills you’d like to learn on the job? What about those skills interests you?",
        "What are your big dreams in life? Are you making progress on them?",
        "What are your goals (for our group for you personally)",
        "What are your long term goals? Have you thought about them?",
        "What are your super powers? What powers would you like to develop?",
        "What areas of your job do you find difficult that getting better skills at would help?",
        "What big questions do you have about your career opportunities in the future?",
        "What can I do to take action or make progress on what we talked about today?",
        "What can you do to take action or make progress on what we talked about today?",
        "What capabilities do you want to develop?",
        "What development areas do you want to work on in the coming weeks?",
        "What do you see as the next step in your career?",
        "What do you want to be doing in 5 years? 10 years? 3 years?",
        "What do you want to do in your next job?",
        "What else can I be doing to help you grow/advance in your career?",
        "What goals have you set for your career?",
        "What kind of training or experience would be most helpful to you right now?",
        "What opportunities have you had recently to learn something new?",
        "What other roles here could you see yourself in down the line? Or what areas would you like to explore?",
        "What parts of your job would you like to deepen your skills in or get additional training in?",
        "What professional goals would you like to accomplish in the next 6 to 12 months, and what makes you say that?",
        "What skills are required to reach your goals?",
        "What skills do you have that you think are underutilized?",
        "What skills would you like to develop right now?",
        "What sort of progress have you made on the next steps we discussed last time?",
        "What work are you doing here that you feel is most in line with your long term goals?",
        "What would make this your perfect job?",
        "What would you like to learn about in the future?",
        "What’s one thing we could do today to help you with your long term goals?",
        "Where do you see your career in 1 year, 3 years? What can you do to make sure you reach those goals? How can we as HR help you to reach those goals (assuming the goals relate to the company)?",
        "Where do you see your career in the next (2/5/10) years?",
        "Where do you see yourself in three years? Five years?",
        "Which career or development goals do you feel like you’re not able to focus on right now?",
        "Which part of the work here do you feel as most relevant to your long-term goals? What kinds of projects do you want to take part in to move toward your goals?",
        "Who in the company would you like to learn from? What do you want to learn?"
      ]
    },
    {
      BusinessGoals: [
        "What is the company not doing today that we should do to better compete in the market?",
        "What’s one thing we’d be *crazy* not to do in the next quarter to improve our product?",
        "How could we change our team meetings to be more effective?",
        "If you were CEO, what’s the first thing you’d change?",
        "Do you think our company is loyal to its employees? Why or why not?",
        "Are there any aspects of our culture you wish you could change?",
        "What are your favorite parts about our culture?",
        "Do you feel over-worked, under-worked, or just the right workload?",
        "Why do you think [employee who recently quit] left? What did they tell you?",
        "What would convince you to leave for a job somewhere else?",
        "Which company values do you like the most? Which the least? Why?",
        "What is the #1 Problem at our company? Why?",
        "Do you feel like you’re on the same page with your team? How often do you think you need meetings to ensure you stay that way?",
        "What do you think are the long term prospects of the company?",
        "How many hours a day do you feel you’re productive? How could we help you be more productive?",
        "How could we be more creative or innovative as a company?",
        "What process can be fixed or improved?",
        "What is the most meaningful part of your job?",
        "Are there any aspects of our culture you wish you could change?",
        "Are there any meetings or discussions you feel you should be a part of that you’re not? Are you included in any you don’t want to be a part of?",
        "Are there any problems or issues that I should know about?",
        "Are there any roles in the company you’d like to learn more about?",
        "Are you uncomfortable giving any of your peers constructive criticism? If so, why?",
        "Can you share some of the details around that particular issue? (Who was involved? Where? When? For how long?)",
        "Could you tell me a little more about that?",
        "Do you feel adequately supported by other team members? What makes you say that?",
        "Do you feel like you’re on the same page with the team? How often do you think you need meetings to ensure you stay that way?",
        "Do you have a clear understanding of the new goals and expectations? What makes you say that?",
        "Do you help other members on the team? Do others help you when you need it?",
        "Has anyone on the team ever made you feel uncomfortable? What happened?",
        "How are you feeling about the company’s future overall? What makes you say that?",
        "How are you feeling about the recent news? Why do you say that?",
        "How could we be more creative or innovative as a company?",
        "How could we change our team meetings to be more effective?",
        "How is the new situation/development affecting your work? What could be getting in the way of your being effective?",
        "How well do you feel like you relate to you coworkers? Do you view them as friends, acquaintances, or strangers?",
        "How would you describe the division of work among team members?",
        "How would you describe the personality of the team? What sort of person would be a good fit here? What sort of person would add something we're currently missing?",
        "How would you rate our communication as a team?",
        "How would you say we're doing at working together as team? What makes you say that?",
        "If we could improve in any way, how would we do it?",
        "If you were CEO, what’s the first thing you’d change?",
        "Is any part of your project unclear or confusing?",
        "Is everyone pulling their weight on the team?",
        "Is there a situation you’d like my help with?",
        "Is there anybody in the team that you find it difficult to work with? Can you tell me why?",
        "Is there anything blocking you from getting your work done?",
        "Is there anything that’s slowing you down from getting your work done?",
        "Is there anything you’d like to see change about the team, and if so, why?",
        "Is your job what you expected when you accepted it?"
      ]
    },
    {
      ManagerImprovement: [
        "What could I do as a manager to make your work easier?",
        "What do you like about my management style? What do you dislike?",
        "Would you like more or less direction from me on your work?",
        "What could I do to make you enjoy your work more?",
        "How can I better support you?",
        "What would you like to know about me?",
        "Is there a situation you’d like my help with?",
        "What is something I could do better? What is a criticism you have for me?",
        "Is there anything I should know about how you like to work?",
        "How can I help you to be successful?",
        "How could I be helping you to be a better manager?",
        "What decisions can I help you make?",
        "What question should I be asking that I haven’t asked yet?",
        "What additional resources from me would be helpful for you as you solve this problem?",
        "What are some possible ways to get the solution you need?",
        "What are some ways we could improve at teamwork? What makes you say that?",
        "What are we doing that you think we should stop doing, and why?",
        "What are we not doing that we should be doing? What makes you say that?",
        "What are your favorite parts about our culture?",
        "What are your next steps to make progress on this problem?",
        "What are your top three motivators?",
        "What area of the company would you like to learn more about?",
        "What areas are ahead of schedule?",
        "What characteristics make someone a good fit for our team? How would you look for those characteristics in an interview?",
        "What concerns do you have about the change that haven't been addressed?",
        "What could you have done differently?",
        "What do you do when you get stuck on something? What is your process of getting unstuck? Who is the team member you turn to for help?",
        "What do you like about working here? What’s not fun about working here?",
        "What do you think about the amount of feedback in our team? When do others give feedback to you? Would you like to hear more feedback from other team member and me?",
        "What do you think about _________?",
        "What do you think are the key skills for your role? How would you rate yourself for each of them?",
        "What do you think would help us work together better?",
        "What do you think you can do to fix that problem?",
        "What excites you about our business? The company? What concerns you?",
        "What is the #1 Problem at our company? Why?",
        "What is the company not doing today that we should do to better compete in the market?",
        "What kind of communication or information do you wish you had more of?",
        "What part of your job do you wish you didn’t have to do?",
        "What sort of resources could you use right now to make things more manageable?",
        "What would you like to learn more about this year?",
        "What would you like to see change here? Why do you say that?",
        "What’s an inexpensive thing we could do to improve our office environment for the team?",
        "What’s going well and not so well with the new situation/development? Why do you think this might be happening?",
        "What’s one thing we should change about how our team works together?",
        "What’s one thing we’d be crazy not to do in the next quarter to improve our product?",
        "What’s something you feel is undervalued that you contribute to the team?",
        "What’s the biggest opportunity we’re missing out on?",
        "What’s the biggest thing you’d like to change about our team?",
        "What’s the No. 1 problem with our organization, and what do you think's causing it?",
        "What’s the No. 1 problem with our organization? Why?",
        "What’s the number one problem within our organization? Why?",
        "Where do you think we can do better?",
        "Which areas would you would like more feedback on?",
        "Which company values do you like the most? Which the least? Why?",
        "Who are you friends with at work? (Shown to be a key to enjoying your job)",
        "Who do you admire within the company and why?",
        "Who has really been kicking ass lately?",
        "Who inspire you in the team? Whose opinions do you respect? What have they done?",
        "Who is kicking ass on the team? What have they done?",
        "Who is really kicking ass in the company? Who do you admire?",
        "Who on the team do you have the most difficulty working with? Why?",
        "Who would you like to work more often with? Why?",
        "Whom in the team do you want to learn from? Whom do you get valuable feedback from?",
        "Why do you think [employee who recently quit] left? What did they tell you?",
        "Are there any obstacles I can remove for you?",
        "As your manager, what would you like me to stop, start, or continue doing?",
        "At what point in the past week were you most frustrated with or discouraged by your work? What can I do to help you manage that?",
        "Do you feel you’re getting enough feedback? Why/why not?",
        "Do you have any feedback for me?",
        "Do you think that you receive enough feedback? Is feedback helpful for your personal development? What can I do to help you get the feedback you want?",
        "How can I better support you?",
        "How can I make your days more fulfilling?",
        "How could I do a better job communicating with you?",
        "How do you prefer to receive feedback?",
        "How might I make this project more challenging or interesting for you?",
        "I'd like to improve as a manager and I could really use your help. Next week, would you be willing to share some feedback on one to two things you think I could do better as your manager?",
        "If you were me, what changes would you make?",
        "I’m trying to make my 1-on-1s better and would appreciate your honest feedback on this one — what did you like about it, and what could be improved?",
        "I’ve noticed that our last several 1-on-1s have stayed pretty surface. What are your honest impressions of this meeting? What could we be doing differently or better?",
        "What additional resources can I provide for you between now and the next time we meet?",
        "What are your impressions of our 1-on-1s? What could we do differently or better?",
        "What are your thoughts on my changes?",
        "What aspect of your job you would like more help or coaching?",
        "What aspects of your work would you like more or less direction from me?",
        "What can I be doing better to help you in your job?",
        "What can I do as a manager to make your work easier?",
        "What can I do better or differently as your manager to support you?",
        "What can I do for you that I'm not?",
        "What can I do to help remove obstacles?",
        "What can I do to help you achieve you current goals and priorities?",
        "What can I do to help you enjoy your work more or remove roadblocks to progress?",
        "What can I do to help you?",
        "What can I do to make things more manageable?",
        "What can I do to make your job easier?",
        "What could I do as a manager to make your work easier?",
        "What do you like about my management style? What do you dislike?",
        "What do you think I should know about the project, but might not?",
        "What have your past managers done that you’d like me to also do or not do?",
        "What is something I could do better? What feedback do you have for me?",
        "What is something I could have done better? What are the situations that I could have helped more but didn’t?",
        "What is the biggest challenge you are currently facing? How can I help with that?",
        "What is the one thing that you need the most from me?",
        "What is the percentage of my involvement in your daily tasks? Would you prefer more or less?",
        "What would you like to know about me?",
        "What would you like to see change about these discussions? How could we make them more useful for you?",
        "What’s your favorite thing I do as a manager of this team I should keep doing?",
        "Where do you think I can be most helpful?",
        "Which areas would you like more or less direction from me on your work?",
        "Would you like more coaching? What aspect of your job do you like more help and coaching on?"
      ]
    },
    {
      Happiness: [
        "Are you happy working here?",
        "Are you happy with your recent work? Why or why not?",
        "What would make you leave this job for another?",
        "What’s one thing we do to help you enjoy your job more?",
        "Is your job what you expected when you accepted it?",
        "What worries you?",
        "What are you really enjoying in your work at the moment?",
        "What is frustrating you about your work at the moment?",
        "Are we getting the most important things right?",
        "What would help you do your job better?",
        "What’s on your mind?",
        "What’s one cool thing that happened to you this week – workwise or otherwise?",
        "What’s not fun about working here? What do you enjoy most about working here?",
        "When was the time you enjoyed working here the most?",
        "What do you feel is your greatest accomplishment here?",
        "What’s something you feel is undervalued that you contribute to the team?",
        "What part of your job do you wish you didn’t have to do?"
      ]
    },
    {
      TeamRelations: [
        "Who on the team do you have the most difficulty working with? Why?",
        "How would you describe the work environment on the team? Is it more competitive or collaborative?",
        "How could we improve the ways our team works together?",
        "Who is kicking ass on the team? What have they done?",
        "Who do you admire on the team? Why?",
        "Do you feel your ideas are heard by the team and I?",
        "Who would you like to work more often with? Why?",
        "Is everyone pulling their weight on the team?",
        "Do you help other members on the team? Do others help you when you need it?",
        "What’s one thing we should change about how our team works together?",
        "What characteristics make someone a good fit for our team? How would you look for those characteristics in an interview?",
        "What’s the biggest thing you’d like to change about our team?",
        "What do you like most about working on our team?",
        "Has anyone on the team ever made you feel uncomfortable? What happened?",
        "How are things going with your team?",
        "How is morale among your direct reports?",
        "How effectively are your team working together?",
        "What are your bottlenecks (for you and/or your team)?",
        "What are some new things you are doing/attempting with your team?",
        "What happens in your individual catch-ups with your direct reports?"
      ]
    }
  ]
};
